pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  prepare:
    image: docker.twistbioscience-staging.com/devops_slave_ecommerce_client_node
    pull: true
    commands:
      - npm install

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  test:
    image: docker.twistbioscience-staging.com/devops_slave_ecommerce_client_node
    commands:
      - npm run lint
      - npm run test:ci
